### ISSUE TITLE
History of ASN's BGPRanking

### ISSUE THREAD

**Issue by DuhaAlasiri** [D4-project/BGP-Ranking#10]
It would be amazing if we could get the historical BGP-Ranking of an ASN when querying it, It will incredibly help in (ASs investigation) specially when investigating old malicious ASN cases.

That was possible before with your CSV output, wonder if it's possible to get one currently. If not, is there any other similar solution?

Kindest regards.

**Comment by Rafiot** [comment]
There is no CSV export anymore, but there should be a json output, which is broken as we speak:  https://github.com/D4-project/BGP-Ranking/blob/master/website/web/__init__.py#L261

I'll try to fix that soon.

**Comment by Rafiot** [comment]
Fixed! 
```bash
curl -X POST -d '{"asn": "5577"}' https://bgpranking-ng.circl.lu/json/asn_history

```
